name: Update Submodules and Run Tests

on:
  repository_dispatch:
    types: [update-submodules-dev]

permissions:
  contents: write

jobs:
  update-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
          
      - name: Switch to 'dev' branch
        run: |
          git fetch origin dev
          git checkout dev
          git reset --hard origin/dev

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"


      - name: test list
        run: |
          cd Foeder-Backend/
          ls

      - name: Git Submodule Update
        run: |
          git submodule foreach 'git fetch origin dev && git checkout origin dev && git pull origin dev'
          
      - name: Commit
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.CI_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"

      - name: Build Docker Compose
        run: docker compose build

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Run Playwright E2E Tests
        run: |
          npm install -g playwright
          playwright test

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
