name: Update Submodules and Run Tests Dev

on:
  repository_dispatch:
    types: [update-submodules-dev]

permissions:
  contents: write

jobs:
  update-and-test:
    runs-on: ubuntu-latest
    env:
      foederLoginEmail: ${{ secrets.FOEDER_LOGIN_EMAIL }}
      foederLoginPass: ${{ secrets.FOEDER_LOGIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
          fetch-depth: 0
          
      - name: Switch to 'dev' branch
        run: |
          git fetch origin dev
          git checkout dev
          git reset --hard origin/dev

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Git Submodule Update
        run: |
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch origin
          git branch -r
          cd ./Foeder-Backend/
          git checkout -b dev origin/dev || git branch -u origin/dev dev
          git pull origin dev
          cd .. 
          cd ./Foeder-Frontend/
          git checkout -b dev origin/dev || git branch -u origin/dev dev
          git pull origin dev
          
      - name: Commit
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.CI_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"

      - name: mkdir if it doesn't exist
        run: |
          cd ./Foeder-Frontend/Foeder-Frontend
          mkdir -p certs
          ls
          
      - name: Build Docker Compose
        run: docker compose build

      - name: Start Docker Compose and run tests
        run: |
          docker compose up -d

      - name: Wait for Frontend
        run: |
          npx wait-on --timeout 30000 https://localhost:5173

      - name: Run Playwright E2E Tests
        run: |
          docker compose exec frontend /bin/bash -c "
          npm install dotenv &&
          npm install playwright &&
          npm install @playwright/test &&
          npm install playwright-extra &&
          npm install puppeteer-extra-plugin-stealth &&
          npx playwright install-deps &&
          npx playwright install &&
          npx playwright test --trace on"

      - name: Copy Playwright trace files
        if: failure()
        run: |
            docker cp foeder-frontend-1:/app/test-results ./Foeder-Frontend/Foeder-Frontend/test-results
            
      - name: Upload Playwright trace
        if: failure() 
        uses: actions/upload-artifact@v3
        with:
          name: playwright-trace
          path: './Foeder-Frontend/Foeder-Frontend/test-results/**/*.zip'
          
      - name: Stop Docker Compose
        if: always()
        run: docker compose down
        
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: static-code-dev
